server:
  port: 8085
hm:
  swagger:
    title: 交易服务接口文档
    package: com.hmall.trade.controller
    description: 交易服务接口文档
  db:
    database: hm-trade
spring:
  rabbitmq:
    host: 192.168.88.140 # 你的虚拟机IP
    port: 5672 # 端口
    virtual-host: /hmall # 虚拟主机
    username: hmall # 用户名
    password: 123 # 密码